"""Retrieval-domain primitives and constrained query-time adapters."""

from hybrid_rag.retrieval.bm25 import (
    BM25_SCORER_VERSION,
    DEFAULT_BM25_B,
    DEFAULT_BM25_K1,
    LEXICAL_TOKENIZER_VERSION,
    BM25Config,
    BM25Hit,
    BM25Scorer,
    tokenize_lexical,
)
from hybrid_rag.retrieval.embedding import (
    EmbeddingConfigurationError,
    EmbeddingProvider,
    HashEmbeddingProvider,
    OpenAICompatibleEmbeddingProvider,
    cosine_similarity,
)
from hybrid_rag.retrieval.fusion import (
    rank_ids,
    select_token_budget,
    weighted_average_fusion,
    weighted_fusion,
)
from hybrid_rag.retrieval.models import (
    INDEX_TEXT_SCHEMA_VERSION,
    RETRIEVAL_SCHEMA_VERSION,
    CandidateHit,
    ContextItem,
    GraphPath,
    IndexBuildReport,
    IndexSemanticConfig,
    RetrievalMode,
    RetrievalResult,
    RetrievalTrace,
    RouteTrace,
    ScoreComponent,
)
from hybrid_rag.retrieval.prompts import build_answer_messages, build_keyword_messages
from hybrid_rag.retrieval.query import (
    DeepSeekQueryClient,
    DeterministicQueryClient,
    EvidenceAnswerer,
    EvidenceItem,
    GroundedAnswer,
    KeywordExtraction,
    KeywordExtractor,
    OpenAICompatibleQueryClient,
    QueryClient,
    QueryConfigurationError,
    QueryValidationError,
    QueryValidationFailureKind,
    QueryValidationIssue,
    deterministic_answer,
    deterministic_keywords,
    validate_answer_completion,
    validate_keyword_completion,
)
from hybrid_rag.retrieval.service import AnswerResult, RetrievalOptions, RetrievalService

__all__ = [
    "BM25_SCORER_VERSION",
    "DEFAULT_BM25_B",
    "DEFAULT_BM25_K1",
    "INDEX_TEXT_SCHEMA_VERSION",
    "LEXICAL_TOKENIZER_VERSION",
    "RETRIEVAL_SCHEMA_VERSION",
    "AnswerResult",
    "BM25Config",
    "BM25Hit",
    "BM25Scorer",
    "CandidateHit",
    "ContextItem",
    "DeepSeekQueryClient",
    "DeterministicQueryClient",
    "EmbeddingConfigurationError",
    "EmbeddingProvider",
    "EvidenceAnswerer",
    "EvidenceItem",
    "GraphPath",
    "GroundedAnswer",
    "HashEmbeddingProvider",
    "IndexBuildReport",
    "IndexSemanticConfig",
    "KeywordExtraction",
    "KeywordExtractor",
    "OpenAICompatibleEmbeddingProvider",
    "OpenAICompatibleQueryClient",
    "QueryClient",
    "QueryConfigurationError",
    "QueryValidationError",
    "QueryValidationFailureKind",
    "QueryValidationIssue",
    "RetrievalMode",
    "RetrievalOptions",
    "RetrievalResult",
    "RetrievalService",
    "RetrievalTrace",
    "RouteTrace",
    "ScoreComponent",
    "build_answer_messages",
    "build_keyword_messages",
    "cosine_similarity",
    "deterministic_answer",
    "deterministic_keywords",
    "rank_ids",
    "select_token_budget",
    "tokenize_lexical",
    "validate_answer_completion",
    "validate_keyword_completion",
    "weighted_average_fusion",
    "weighted_fusion",
]
