"""Retrieval-domain primitives and constrained query-time adapters."""

from hybrid_rag.retrieval.embedding import (
    EmbeddingConfigurationError,
    EmbeddingProvider,
    HashEmbeddingProvider,
    OpenAICompatibleEmbeddingProvider,
    cosine_similarity,
)
from hybrid_rag.retrieval.fusion import rank_ids, select_token_budget, weighted_fusion
from hybrid_rag.retrieval.models import (
    INDEX_TEXT_SCHEMA_VERSION,
    RETRIEVAL_SCHEMA_VERSION,
    CandidateHit,
    ContextItem,
    GraphPath,
    IndexBuildReport,
    IndexSemanticConfig,
    RetrievalMode,
    RetrievalResult,
    RetrievalTrace,
    RouteTrace,
)
from hybrid_rag.retrieval.prompts import build_answer_messages, build_keyword_messages
from hybrid_rag.retrieval.query import (
    DeepSeekQueryClient,
    DeterministicQueryClient,
    EvidenceAnswerer,
    EvidenceItem,
    GroundedAnswer,
    KeywordExtraction,
    KeywordExtractor,
    OpenAICompatibleQueryClient,
    QueryClient,
    QueryConfigurationError,
    QueryValidationError,
    QueryValidationFailureKind,
    QueryValidationIssue,
    deterministic_answer,
    deterministic_keywords,
    validate_answer_completion,
    validate_keyword_completion,
)
from hybrid_rag.retrieval.service import AnswerResult, RetrievalOptions, RetrievalService

__all__ = [
    "INDEX_TEXT_SCHEMA_VERSION",
    "RETRIEVAL_SCHEMA_VERSION",
    "AnswerResult",
    "CandidateHit",
    "ContextItem",
    "DeepSeekQueryClient",
    "DeterministicQueryClient",
    "EmbeddingConfigurationError",
    "EmbeddingProvider",
    "EvidenceAnswerer",
    "EvidenceItem",
    "GraphPath",
    "GroundedAnswer",
    "HashEmbeddingProvider",
    "IndexBuildReport",
    "IndexSemanticConfig",
    "KeywordExtraction",
    "KeywordExtractor",
    "OpenAICompatibleEmbeddingProvider",
    "OpenAICompatibleQueryClient",
    "QueryClient",
    "QueryConfigurationError",
    "QueryValidationError",
    "QueryValidationFailureKind",
    "QueryValidationIssue",
    "RetrievalMode",
    "RetrievalOptions",
    "RetrievalResult",
    "RetrievalService",
    "RetrievalTrace",
    "RouteTrace",
    "build_answer_messages",
    "build_keyword_messages",
    "cosine_similarity",
    "deterministic_answer",
    "deterministic_keywords",
    "rank_ids",
    "select_token_budget",
    "validate_answer_completion",
    "validate_keyword_completion",
    "weighted_fusion",
]
